# Generated by Django 3.1.14 on 2022-03-22 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_manzil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='manzil',
        ),
    ]
